# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_commercial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commercial',
        ),
    ]
