# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=5000)),
            ],
        ),
    ]
