# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
