# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20161210_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
